from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Main_GUI_Widget(object):
    def setupUi(self, Main_GUI_Widget):
        Main_GUI_Widget.setObjectName(_fromUtf8("Main_GUI_Widget"))
        Main_GUI_Widget.resize(793, 550)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setBold(False)
        font.setWeight(50)
        Main_GUI_Widget.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../icrc.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main_GUI_Widget.setWindowIcon(icon)
        self.label = QtGui.QLabel(Main_GUI_Widget)
        self.label.setGeometry(QtCore.QRect(270, 20, 241, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setIndent(-1)
        self.label.setObjectName(_fromUtf8("label"))
        self.line = QtGui.QFrame(Main_GUI_Widget)
        self.line.setGeometry(QtCore.QRect(373, 90, 20, 391))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.Add_button = QtGui.QPushButton(Main_GUI_Widget)
        self.Add_button.setGeometry(QtCore.QRect(220, 430, 111, 41))
        self.Add_button.setObjectName(_fromUtf8("Add_button"))
        self.Add_Data_comboBox = QtGui.QComboBox(Main_GUI_Widget)
        self.Add_Data_comboBox.setGeometry(QtCore.QRect(20, 440, 151, 22))
        self.Add_Data_comboBox.setObjectName(_fromUtf8("Add_Data_comboBox"))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.Add_Data_comboBox.addItem(_fromUtf8(""))
        self.View_Data_Button = QtGui.QPushButton(Main_GUI_Widget)
        self.View_Data_Button.setGeometry(QtCore.QRect(130, 260, 111, 41))
        self.View_Data_Button.setObjectName(_fromUtf8("View_Data_Button"))
        self.label_2 = QtGui.QLabel(Main_GUI_Widget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.line_2 = QtGui.QFrame(Main_GUI_Widget)
        self.line_2.setGeometry(QtCore.QRect(20, 90, 301, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_3 = QtGui.QLabel(Main_GUI_Widget)
        self.label_3.setGeometry(QtCore.QRect(60, 390, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line_3 = QtGui.QFrame(Main_GUI_Widget)
        self.line_3.setGeometry(QtCore.QRect(20, 410, 301, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.groupBox = QtGui.QGroupBox(Main_GUI_Widget)
        self.groupBox.setGeometry(QtCore.QRect(390, 150, 181, 91))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.Delete_button = QtGui.QPushButton(self.groupBox)
        self.Delete_button.setGeometry(QtCore.QRect(30, 30, 111, 41))
        self.Delete_button.setObjectName(_fromUtf8("Delete_button"))
        self.groupBox_2 = QtGui.QGroupBox(Main_GUI_Widget)
        self.groupBox_2.setGeometry(QtCore.QRect(580, 150, 181, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Update_button = QtGui.QPushButton(self.groupBox_2)
        self.Update_button.setGeometry(QtCore.QRect(30, 30, 111, 41))
        self.Update_button.setObjectName(_fromUtf8("Update_button"))
        self.groupBox_3 = QtGui.QGroupBox(Main_GUI_Widget)
        self.groupBox_3.setGeometry(QtCore.QRect(390, 330, 181, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.Search_button = QtGui.QPushButton(self.groupBox_3)
        self.Search_button.setGeometry(QtCore.QRect(30, 30, 111, 41))
        self.Search_button.setObjectName(_fromUtf8("Search_button"))
        self.groupBox_4 = QtGui.QGroupBox(Main_GUI_Widget)
        self.groupBox_4.setGeometry(QtCore.QRect(580, 330, 181, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.Report_button = QtGui.QPushButton(self.groupBox_4)
        self.Report_button.setGeometry(QtCore.QRect(40, 30, 101, 41))
        self.Report_button.setObjectName(_fromUtf8("Report_button"))
        self.layoutWidget = QtGui.QWidget(Main_GUI_Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 110, 344, 101))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Asistira_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Asistira_checkBox.setObjectName(_fromUtf8("Asistira_checkBox"))
        self.verticalLayout.addWidget(self.Asistira_checkBox)
        self.Kirurg_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Kirurg_checkBox.setObjectName(_fromUtf8("Kirurg_checkBox"))
        self.verticalLayout.addWidget(self.Kirurg_checkBox)
        self.Konzultant_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Konzultant_checkBox.setObjectName(_fromUtf8("Konzultant_checkBox"))
        self.verticalLayout.addWidget(self.Konzultant_checkBox)
        self.Nadgleda_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Nadgleda_checkBox.setObjectName(_fromUtf8("Nadgleda_checkBox"))
        self.verticalLayout.addWidget(self.Nadgleda_checkBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Operacije_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Operacije_checkBox.setObjectName(_fromUtf8("Operacije_checkBox"))
        self.verticalLayout_2.addWidget(self.Operacije_checkBox)
        self.Pacijent_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Pacijent_checkBox.setObjectName(_fromUtf8("Pacijent_checkBox"))
        self.verticalLayout_2.addWidget(self.Pacijent_checkBox)
        self.Privatni_pacijent_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Privatni_pacijent_checkBox.setObjectName(_fromUtf8("Privatni_pacijent_checkBox"))
        self.verticalLayout_2.addWidget(self.Privatni_pacijent_checkBox)
        self.Sala_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Sala_checkBox.setObjectName(_fromUtf8("Sala_checkBox"))
        self.verticalLayout_2.addWidget(self.Sala_checkBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Sestra_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Sestra_checkBox.setObjectName(_fromUtf8("Sestra_checkBox"))
        self.verticalLayout_3.addWidget(self.Sestra_checkBox)
        self.Soba_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Soba_checkBox.setObjectName(_fromUtf8("Soba_checkBox"))
        self.verticalLayout_3.addWidget(self.Soba_checkBox)
        self.Zaduzena_za_salu_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Zaduzena_za_salu_checkBox.setObjectName(_fromUtf8("Zaduzena_za_salu_checkBox"))
        self.verticalLayout_3.addWidget(self.Zaduzena_za_salu_checkBox)
        self.Zaduzena_za_sobu_checkBox = QtGui.QCheckBox(self.layoutWidget)
        self.Zaduzena_za_sobu_checkBox.setObjectName(_fromUtf8("Zaduzena_za_sobu_checkBox"))
        self.verticalLayout_3.addWidget(self.Zaduzena_za_sobu_checkBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Main_GUI_Widget)
        QtCore.QMetaObject.connectSlotsByName(Main_GUI_Widget)

    def retranslateUi(self, Main_GUI_Widget):
        Main_GUI_Widget.setWindowTitle(_translate("Main_GUI_Widget", "BP Za bolnicu", None))
        self.label.setText(_translate("Main_GUI_Widget", "Baza Podataka za bolnicu", None))
        self.Add_button.setText(_translate("Main_GUI_Widget", "Add", None))
        self.Add_Data_comboBox.setItemText(0, _translate("Main_GUI_Widget", "Asistira", None))
        self.Add_Data_comboBox.setItemText(1, _translate("Main_GUI_Widget", "Kirurg", None))
        self.Add_Data_comboBox.setItemText(2, _translate("Main_GUI_Widget", "Konzultant", None))
        self.Add_Data_comboBox.setItemText(3, _translate("Main_GUI_Widget", "Nadgleda", None))
        self.Add_Data_comboBox.setItemText(4, _translate("Main_GUI_Widget", "Operacija", None))
        self.Add_Data_comboBox.setItemText(5, _translate("Main_GUI_Widget", "Pacijent", None))
        self.Add_Data_comboBox.setItemText(6, _translate("Main_GUI_Widget", "Privatni pacijent", None))
        self.Add_Data_comboBox.setItemText(7, _translate("Main_GUI_Widget", "Sala", None))
        self.Add_Data_comboBox.setItemText(8, _translate("Main_GUI_Widget", "Sestra", None))
        self.Add_Data_comboBox.setItemText(9, _translate("Main_GUI_Widget", "Soba", None))
        self.Add_Data_comboBox.setItemText(10, _translate("Main_GUI_Widget", "Zaduzena za salu", None))
        self.Add_Data_comboBox.setItemText(11, _translate("Main_GUI_Widget", "Zaduzena za sobu", None))
        self.View_Data_Button.setText(_translate("Main_GUI_Widget", "View Data", None))
        self.label_2.setText(_translate("Main_GUI_Widget", "View Data", None))
        self.label_3.setText(_translate("Main_GUI_Widget", "Add Data", None))
        self.groupBox.setTitle(_translate("Main_GUI_Widget", "Delete row of data from a table", None))
        self.Delete_button.setText(_translate("Main_GUI_Widget", "Delete", None))
        self.groupBox_2.setTitle(_translate("Main_GUI_Widget", "Update data ", None))
        self.Update_button.setText(_translate("Main_GUI_Widget", "Update", None))
        self.groupBox_3.setTitle(_translate("Main_GUI_Widget", "Search for specific data", None))
        self.Search_button.setText(_translate("Main_GUI_Widget", "Search", None))
        self.groupBox_4.setTitle(_translate("Main_GUI_Widget", "Create a printable report", None))
        self.Report_button.setText(_translate("Main_GUI_Widget", "Report", None))
        self.Asistira_checkBox.setText(_translate("Main_GUI_Widget", "Asistira", None))
        self.Kirurg_checkBox.setText(_translate("Main_GUI_Widget", "Kirurg", None))
        self.Konzultant_checkBox.setText(_translate("Main_GUI_Widget", "Konzultant", None))
        self.Nadgleda_checkBox.setText(_translate("Main_GUI_Widget", "Nadgleda", None))
        self.Operacije_checkBox.setText(_translate("Main_GUI_Widget", "Operacija", None))
        self.Pacijent_checkBox.setText(_translate("Main_GUI_Widget", "Pacijent", None))
        self.Privatni_pacijent_checkBox.setText(_translate("Main_GUI_Widget", "Privatni pacijent", None))
        self.Sala_checkBox.setText(_translate("Main_GUI_Widget", "Sala", None))
        self.Sestra_checkBox.setText(_translate("Main_GUI_Widget", "Sestra", None))
        self.Soba_checkBox.setText(_translate("Main_GUI_Widget", "Soba", None))
        self.Zaduzena_za_salu_checkBox.setText(_translate("Main_GUI_Widget", "Zaduzena za salu", None))
        self.Zaduzena_za_sobu_checkBox.setText(_translate("Main_GUI_Widget", "Zaduzena za sobu", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Main_GUI_Widget = QtGui.QWidget()
    ui = Ui_Main_GUI_Widget()
    ui.setupUi(Main_GUI_Widget)
    Main_GUI_Widget.show()
    sys.exit(app.exec_())

